### ISSUE TITLE
File upload exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#142] opened 2023-06-17 08:37 UTC
![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/4b80cae7-3688-4c8e-bdee-687f52bbbd65)

**Comment by wu-clan** [comment] 2023-06-17 09:22
Hi, @downdawn 

Can you provide pseudo-code? How to trigger this error

Known UploadFile type error, fixed in #145

**Comment by wu-clan** [comment] 2023-06-17 09:28
This is the pseudo code of the official fastapi documentation, which can be used for form testing

```python
@router.post('/files/', summary='文件上传')
async def create_file(
        file: bytes = File(), fileb: UploadFile | None = File(default=None)
):
    return {
        'file_size': len(file),
        'fileb_content_type': fileb.content_type,
    }
```

Since the project does not use the Form() entry, More pseudocode may be needed

**Comment by wu-clan** [comment] 2023-06-17 09:54
I get a magic `400 Bad Request` print and swagger output `{ "detail": "There was an error parsing the body" }`, but I did not meet your mistake.

**Comment by downdawn** [comment] 2023-06-17 10:12
```
@router.post('/upload', summary='上传文件')
async def upload_file(file: UploadFile = File(...)):
    # TODO 上传文件
    print(file.filename)
    return await response_base.success()

```

**Comment by downdawn** [comment] 2023-06-17 10:52
> I get a magic `400 Bad Request` print and swagger output `{ "detail": "There was an error parsing the body" }`, but I did not meet your mistake.

Yes, same error.

The console output is abnormal:
```
sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type UploadFile is not JSON serializable
```

**Comment by wu-clan** [comment] 2023-06-17 10:54
This bug will be fixed in the PR above, I haven't merged it yet

**Comment by wu-clan** [comment] 2023-06-17 10:56
I seem to have found the cause of the anomaly:

https://github.com/tiangolo/fastapi/blob/49bc3e0873c8e89edbffdd3a41b1c2c56f15c823/fastapi/routing.py#L198-L202

After tracing, it will come to AbstractAsyncContextManager, probably because the stream is not closed

**Comment by downdawn** [comment] 2023-06-17 14:06
This PR does not solve this problem

**Comment by wu-clan** [comment] 2023-06-17 15:10
Yes, it only solves the other problems found, request.form() is not handled

**Comment by wu-clan** [comment] 2023-06-17 15:11
Yes, it only solves the other problems found, request.form() hasn't been processed yet

**Comment by downdawn** [comment] 2023-06-20 02:35
Any ideas?

I traced to wrapped_rcv_gen, can't get into

**Comment by wu-clan** [comment] 2023-06-20 03:23
Not yet, I'm updating on the time module

This involves ASGI principles and internal design of the framework, not very good solution, should look for the answer in Starlette, the main problem should be: in pure ASGI middleware happend exception when using form() + body() + json()

But a reminder is that when using File() to transfer data, json() method may fail

**Comment by downdawn** [comment] 2023-06-20 03:44
Tracked to fastapi/routing exception

![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/38d59f73-44b8-441e-b93f-7d7f1e700d79)

Executing request.form() throws an exception
```
AttributeError: 'AwaitableOrContextManagerWrapper' object has no attribute 'entered'
```

**Comment by downdawn** [comment] 2023-06-20 03:59
Upload requests are temporarily added to OPERA_LOG_EXCLUDE

**Comment by downdawn** [comment] 2023-08-15 03:58
Hi, @wu-clan 

I get exception when i use StreamingResponse
```
return StreamingResponse(generate(), media_type="text/event-stream")
```
```
  File "/backend/app/middleware/opera_log_middleware.py", line 108, in wrapped_rcv_gen
    async for message in request.receive:  # type: ignore
TypeError: 'async for' requires an object with __aiter__ method, got method
```
"OperaLogMiddleware" seems to have an unavoidable issue. Could it be elevated to a P0 priority? Prioritize resolving it.

**Comment by wu-clan** [comment] 2023-08-15 04:29
generate() is it an iterator function?

**Comment by wu-clan** [comment] 2023-08-15 04:37
1. Due to Starlette's design, it may never be possible to use request.form() in middleware.
2. A major update took place in Starlette>=0.28.0, but fastapi has never upgraded it, so I haven't tried to update it again.
3. I will take a look at it again and try to avoid other problems.

**Comment by downdawn** [comment] 2023-08-15 08:26
> generate() is it an iterator function?

yes

**Comment by wu-clan** [comment] 2023-08-23 14:15
Observe changes: https://github.com/tiangolo/fastapi/pull/9636

**Comment by wu-clan** [comment] 2023-12-17 13:52
After a long time, I picked this up again. 

There seems to be a comprehensive solution:
https://github.com/tiangolo/fastapi/discussions/8187

**Comment by wu-clan** [comment] 2023-12-17 13:56
But I'm not sure if these work properly when FastAPI upgrade Starlette > 0.28.0, so I choose to wait and see.

**Comment by downdawn** [comment] 2023-12-18 05:34
[https://github.com/tiangolo/fastapi/discussions/8187#discussioncomment-5148057](https://github.com/tiangolo/fastapi/discussions/8187#discussioncomment-5148057)

The solution is from 2021; maybe we can consider it after upgrading to p-v2.

**Comment by wu-clan** [comment] 2023-12-28 16:42
I'm sorry I deleted a lot of outdated conversations, but I still have a lot of confusion about this question. 

`request.form()` is the source of disaster.

Https://github.com/encode/starlette/discussions/1933

**Comment by wu-clan** [comment] 2023-12-29 17:22
It is worth noting that errors still occur when the file upload parameter is optional, which may be a problem in FastAPI. 

PR did not test other response modes (StreamingResponse...). 

Wait and see: https://github.com/tiangolo/fastapi/issues/10857

**Closed** 2024-01-03 14:23 UTC
